## 1
library(tree)

## 2
setwd("/home/marcus/Documents/Rwork/R exercises/")

#Note: "for_Ex7_pt2.csv" generated by pt1 of this exercise
Data <- read.csv("for_Ex7_pt2.csv", stringsAsFactors =  TRUE)

## 3
set.seed(111)
Data$test <- sample(c(rep(TRUE,round(22*.3)),rep(FALSE,round(22*.7))))
Train <- Data[!(Data$test),]
Test <- Data[(Data$test),]

## 4
model1 <- tree(class ~. , data = Train)

## 5
plot(model1)
text(model1)

## 6
pred_class <- predict(model1,Test, type = "class")

## 7
table(pred_class,Test$class)

## 8
summary(model1)
# Observation: the Misclassification error rate is 0.3077 = 4 / 13 

## 9
mean(Test$class != pred_class)

## 10
#Observation: the misclassification error rate is worse with the train data than the train data.
#             We may improve the model by increasing the number of data points.
#             It would be difficult to prune the model due to the paucity of nodes.